name: UltimateCustomCrafts
version: '${project.version}'
main: sullexxx.ultimatecustomcrafts.UltimateCustomCrafts
api-version: '1.20'
commands:
  ultimatecustomcrafts:
    aliases: ["ucc", "ultimatecc"]
    description: UltimateCustomCrafts command
